config/routes.rb
InstagramClone::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :photos
  resources :tags
  resources :charges

  root 'photos#index'
  

  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image,
                    styles: { medium: "400x400>", thumb: "200x200>" }

  belongs_to :user
  has_and_belongs_to_many :tags
  
  validates :title, length: 3..255
  validates :image, attachment_presence: { message: 'need a photo' }

  def tag_names
    ''
  end

  def tag_names=(tags_string)
    tags_string.split(' ').each do |tag|
      new_tag = Tag.find_or_create_by(name: tag)
      new_tag.slug = new_tag.name.gsub('#', '').downcase

      self.tags << new_tag
    end
  end





end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :photos
  
  def to_param
    slug
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  has_many :photos

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.screen_name = auth.info.nickname
    end
  end

  def not_omniauth?
    provider.blank?
  end

  def password_required?
    not_omniauth?
  end

  def email_required?
    not_omniauth?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :nag_user_for_email

  def nag_user_for_email
    if user_signed_in? && current_user.email.blank?
      flash[:notice] = "Please add an email to your account"
      # redirect_to edit_user_registration_path
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    Order.create(description: 'Photo print', user: current_user)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect user, notice: "Signed in!"
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  before_action :authenticate_user!, except: :index

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = current_user.photos.build(params[:photo].permit(:title, :image, :tag_names))

    if @photo.save
      flash[:notice] = 'Photo added'
      WebsocketRails[:photos].trigger 'new',
                   { title: @photo.title, image_url: @photo.image.url(:medium) }
      redirect_to photos_path
    else
      render 'new'
    end
  end

  def edit
    @photo = current_user.photos.find params[:id]
  end

  def update
    @photo = Photo.find params[:id]
    @photo.update(params[:photo].permit(:title))

    flash[:notice] = 'Photo updated'
    redirect_to photos_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find_by slug: params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper

  def tag_names(photo)
    tag_links = photo.tags.map do |tag|
      link_to(tag.name, tag)
    end

    tag_links.join(", ").html_safe
  end
  
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= ENV['STRIPE_PUBLIC'] %>"
          data-description="A cool print"
          data-amount="500"></script>
<% end %>

app/views/layouts/_user_links.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

<% if user_signed_in? %>
  <li>
  <%= link_to('Edit registration', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path)  %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "InstagramClone" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">InstagramClone</a>
        <div class="nav-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <%= bootstrap_flash %>
          <%= render 'layouts/user_links' %>
          <%= yield %>
        </div>
        <div class="col-md-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/old_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstagramClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/user_links' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo, html: { multipart: true } do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <%= f.label :tag_names, 'Tags' %>
  <%= f.text_field :tag_names %>

  <%= f.submit %>
<% end %>

app/views/photos/_photo.html.erb
<div class='col-md-4'>
  <h3><%= photo.title %></h3>
  <%= image_tag photo.image.url(:thumb), class: 'uploaded-pic' %>
  <caption>Uploaded by <%= photo.user.email if photo.user %></caption>
  <p>Tags:
    <%= tag_names(photo) %>
  </p>
  <button>Buy Print</button>
</div>

app/views/photos/edit.html.erb
<%= render 'form' %>

app/views/photos/index.html.erb
<h1>Photos</h1>
<div class='row photos'>
  <%= render @photos %>
</div>
<h4><%= link_to 'New photo', new_photo_path %></h4>
<h3>There are currently this many tags: <%= Tag.count %></h3>

app/views/photos/new.html.erb
<% if @photo.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>
 
    <ul>
    <% @photo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form' %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<div class='row'>
  <% @tag.photos.each do |photo| %>
    <div class='col-md-4'>
      <h3><%= photo.title %></h3>
      <%= image_tag photo.image.url(:thumb), class: 'uploaded-pic' %>
      <caption>Uploaded by <%= photo.user.email if photo.user %></caption>
      <p>Tags:
        <%= tag_names(photo) %>
      </p>
    </div>
  <% end %>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>